### ISSUE TITLE
Rendering Engine Rewrite

### ISSUE THREAD

**Issue by Chronos-92** [Damian666/Orion-Plus-Game-Engine#10]
Currently working on this over at https://github.com/Chronos-92/Orion-Plus-Game-Engine/tree/new-client

It's heavily work in progress, so expect to see some hefty commits or rewrites every now and then.

**Comment by Chronos-92** [comment]
Put on hold for the time being, I've recently got a new job I need to settle in to and Monogame appears to have some major issues with sound in their latest releases which hinder any progress in fully removing SFML.

**Comment by ParchmentWolf** [comment]
Uhh monogame is well just wrapping over another library that they include so you can always just use that library directly... cant for the life of me remember what it was called, i gave up on the idea of monogame just cause they are constantly getting more and more new problems since they tried to rehaul it xD
