### ISSUE TITLE
Rename the engine to eclipse stable for extra stability

### ISSUE THREAD

**Issue by OddlyDoddly** [Damian666/Orion-Plus-Game-Engine#15]
The engine should be "Eklepze Stable 3 .net edition with extra saucy sadscripting". thx.

**Comment by SpiceyWolf** [comment]
No, that is a horrible idea. 1) This is based on origins which was in NO WAY compatible with ES. 2) Sadscript is fucking garbage, and killed absolute performance and would have to be handmade compatibility as its not natively compatible with .net - essentially the script system would need rebuilt from scratch in .net which already isnt worth the work without that incredibly huge task. 3) ES was horrible, hell even origins is horrible thats why it is moving away from having anything in common with that. All eclipse was terrible it was made in a very limited language(VB6) and made by people as they were learning how to do game development aka the most garbage version of the engine they could have ever built essentially became this. If they had done it from scratch with their knowlege today itd be way smaller, less buggy, and work entirely different than this.

**Comment by SpiceyWolf** [comment]
To be more specific, any scripting of any kind kills performance... and if it should REALLY implement any scripting python would be the best option and least invasive... and even then... still lose alot of performance limiting you to a smaller game.

**Comment by OddlyDoddly** [comment]
@SpiceyWolf It was a joke, i'm stabbing at daymeun. I'm moderately serious about sadscripting though.

Ps: ex dee

**Comment by SpiceyWolf** [comment]
scripting provides only minor convenience for people who for some ungodly reason cant download a friggen IDE and work on the source appropriately... it was more useful in the days of Languages/IDE's being less stable or not having enough HDD space, but it is far less appropriate these days as those arent issues anymore and scripting comes with the benefit of teaching bad coding practices and a lack of full understanding of what they are doing with the code. Which in turn, makes the already slower code slower because the lack of understanding of what they are doing has now probably led them to do unnecessary or extra or broken things in their process as well.. you should really not be any level of serious about sadscripting or any scripting in general.

**Comment by OddlyDoddly** [comment]
No... no that's not what scripting is for. I'm concerned for you. You shouldn't try to implement sadscript, Damian should. He's a pro.

**Comment by SpiceyWolf** [comment]
>_> hes more of a vb6 coder... Ive had to explain some more .net specific stuff to him -> not that hes a bad coder, but hes very unfamiliar with alot of .nets core features that even do powerful things. + the server took about 5 mins to startup before i showed up, now its 3 seconds.

**Comment by SpiceyWolf** [comment]
The engine would be WAAAAAY more improved right now if it werent for me having a project to work on that is very different from this geared toward making actual mmorpg's and i know wtf im talking about.

**Comment by Raven-Quest** [comment]
lol spicey, let him be, he is fucking around lol xD
