### ISSUE TITLE
Just read it guys ;P

### ISSUE THREAD

**Issue by ParchmentWolf** [Damian666/Orion-Plus-Game-Engine#16]
:DELETED:

**Comment by SpiceyWolf** [comment]
So to reiterate a major point, if you encounter weird bugs, one of the most expected of them being that things render totally white for no reason or task manager reporting a massive or constantly growing disk usage or whatever, downgrade to 2.2. If you still encounter the white rendering, either downsize the sprite or tilesheet or whatever the hell is so massive you are trying to render (and i meen the physical file, the render square is irrelevant) or downgrade further to 2.1.

Good luck with your further development, i am proud of the distance youve come since i offered the ... well little help that i did :/

**Comment by Raven-Quest** [comment]
I did not know that...

ill get back to 2.2 just to be sure then :)

you are gonna make a 2.4 portable? I really like the new text functions it brings...

**Comment by SpiceyWolf** [comment]
I wasnt even aware theyd made it to .4 yet o-o -> and it all mostly matters on really how stable it is and documentation. Its not easy making the original wrappers which is why i relied kinda on a shortcut i meen if i HAD to from scratch i could/would, but i would kinda require it to be more stable and worthy of the effort that i could focus on just that 1 wrapper instead of maintaining 4 versions. (Im only maintaining 3 for the simple fact that the further back you go the better the memory management was and stable and the newer the better feature support)

**Comment by Raven-Quest** [comment]
yeah, that's the problem indeed, memory against functions >.<

**Comment by SpiceyWolf** [comment]
Ill have to look into it more, im kinda swamped on my project atm anyway i really gotta refine this project set i have right now cause it needs to be as simple as possible yet maintain enough performance it could basicly run runescape and/or more xD but graphical engine will most likely need updated in the future so ill be forced to look into it sooner or later..

**Comment by Raven-Quest** [comment]
kk, ill just keep doing my thing, you know where to find me :)

**Comment by SpiceyWolf** [comment]
Not only that, again as i mentioned it wasnt even necessarily an issue of their code in sfml between version 2.1 and 2.2 (probably not even 2.3 but i was making work arounds so that broken code that mighta been directly in opengl could be remade or handled differently at the .net level to fix the problem) it was strictly the opengl version that kinda swapped memory for performance and all that xD

**Comment by Raven-Quest** [comment]
ah, ok, well, I would love to have the newer sfml.

when your ready mate ^.^

**Comment by SpiceyWolf** [comment]
Eh, just found someone else has already migrated 2.4 for .net... although they dont often update so im assuming theyve pretty much done whatever they can do to it... If theres any bugs no telling how often ill update, i dont know if itll have the white render issue or not... but i might get around to updating it sometime in the next couple of days to have a fourth since i wont have to do all the work on my own xD

**Comment by Raven-Quest** [comment]
nice :)

**Comment by Raven-Quest** [comment]
cool man :)
