### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by ParchmentWolf** [Damian666/Orion-Plus-Game-Engine#20]
:DELETED:

**Comment by Raven-Quest** [comment]
wut? it works just fine? O.o

easy as fuck even lol

**Comment by SpiceyWolf** [comment]
nah, easy af is pulling an entire xml in just 2-3 lines of code, no matter the size, and not having 2 functions for "if it doesnt have a file then put these values"

**Comment by SpiceyWolf** [comment]
boii u dont know easy till half ur source is gone due to lack of using the languages features :D

**Comment by SpiceyWolf** [comment]
well by that i meant starting to use them makes half the source disappear >.>

**Comment by Raven-Quest** [comment]
don't go chronos on my ass plox xD

**Comment by Raven-Quest** [comment]
you know I like the way its coded now, if you change it to far, I'm done...

speaking in general, not the specific xml code :P

**Comment by pandinocoder** [comment]
@SpiceyWolf: @Damian666 mentioned you were redoing the networking, and if so what are you replacing it with and do you have an ETA on when it'll be done? (And lastly, do you mind pushing a branch with your updated progress so I can keep tabs on what you're doing?)

**Comment by SpiceyWolf** [comment]
I have my own network and some other stuff in a bsd-3clause licensed dll i made much higher performance than the network in here. One of the biggest faults is the fact it generates new threads per client, which is terribly inefficient and would not be managable for high playerbase... myne asynchronously handles all sockets in a single thread which meens the change essentially trades off cpu core limits for cpu performance limits. and ETA? not sure yet Its a royal pain trying to convert in here and i have to reattempt it a good few times just to make sure its being ported in properly... and that theres no bugs. I may have to push a modified VERSION of said network just to make it work as this engine likes everything to start at 1 rather than 0. However the network usage is almost perfectly identical to the VB6 network (doesnt use the bs dictionary invoker that orion uses) -> also higher performance :D

**Comment by SpiceyWolf** [comment]
Also i forked it, gunna push the network mod over the fork and let damian implement it back in as he sees fit.

**Comment by pandinocoder** [comment]
Yeah I'm aware you forked it, I checked out the fork to see only the SFML changes added.

**Comment by pandinocoder** [comment]
@Damian666 Close this (#20) because of this: https://github.com/Damian666/Orion-Plus-Game-Engine/issues/28#issuecomment-284025720
