### ISSUE TITLE
ArchaicIO

### ISSUE THREAD

**Issue by ParchmentWolf** [Damian666/Orion-Plus-Game-Engine#30]
:DELETED:

**Comment by SpiceyWolf** [comment]
Also i guess i should mention since you ARE using VB.net and wouldnt be using the GTK# stuff, id recommend downgrading the SFML.Portable DLL to the 1.0 just so ur not pulling extra unneeded dlls. Sorry about that. (1.1.1/1.1.0 does not include any bug fixes just the added GTK# support for C# users)

**Comment by SpiceyWolf** [comment]
OH SPEAKING OF SFML... You can REALLY optimize the living crap out of the usage by planting an SFML Winforms Control into the form(Since you were using a form anyway) and then simply add the function from its event list for Draw (If this isnt clear what i meen, you know how Form has "Form_Load(sender as object, e as eventargs)"? Well the sfmlcontrol has one for draw just like that you can use)

This would make it so it only draws WHEN the form is updated (Via Application.DoEvents()) and itll save performance like crazy AND you can then utilize the forms KeyPress/KeyDown/KeyUp events instead of making your own by hand and having a bunch of variables you gotta keep track of. itll clean up the code, make for easier read AND usage and prevent some possible bugs :D

**Comment by SpiceyWolf** [comment]
Just wanted to point out... the SFML 2.3 has 2 good things about it, it is not only safe, and has more features and bug fixes, but it also uses an older GL version like 2.1 did, so its a SAFE alternative to 2.1, while even though 2.2 has a few less bug fixes and reduced features it does sport a higher performance more modern GL version so you can take ur pick there.. 2.1/2.3 are good for older pc's that cant handle a good variety of GL versions.

**Comment by Raven-Quest** [comment]
i tried upgrading it to the portable one, but I receive errors on drawing...

**Comment by SpiceyWolf** [comment]
Yeah the nuget is too much a pain in the ass and it was breaking working dllson some posts so I stopped supporting nuget packages. U can get the working version from my github repo which supports even more stuff now and u can manually compile the chit u want in it
