### ISSUE TITLE
Broken Things

### ISSUE THREAD

**Issue by ghost** [Damian666/Orion-Plus-Game-Engine#43]
The Editors crash in automaptile because the xml doc not generated.
ur project is interesting but look like u are programming in vb6, 
i know its E.O based but isn't worth using windows forms and other things in a project when u have a sdl library with gui
i have remaked the e.o in dotnet 3 times, sdl, dx, sfml but i have no time now, 
i go wait for ur project, looks very nice, so many resources *u*
and the network was  unstable, review the connections and exit methods, IsNothing checks etc.
I realized that like me, you are adding many features but forgetting what has already been created, try to review the code, refactor things already created, optimize.
if u can do this will be a great engine.

**Comment by ParchmentWolf** [comment]
I'm skeptical your post isn't purely troll because if you have remade EO in .net 3 times you wouldn't need Orion. As well the maintainer of the engine isn't super experienced with classes or other frameworks he is using the one that Orion's base was built up with (and improved/expanded upon slightly by me) which is SFML. Simply the app running winforms from the client side also doesn't matter because this is a 2D game engine and not a super high-tech one so we don't need 40 thousand+ renders a second, 30fps and you wont see a difference and winforms is more than capable of letting at least that amount.

The network was replaced with one I use for an actual MMO model so if there is a problem with it you should be reporting it to me, rather than saying "Check (Insert-Ambiguous-Syntax-Here)" telling us go hunt out bugs does nothing if you don't actually report specific problems. We have other things to do and are not going to spend hours and hours looking for bugs that possibly don't exist half the time.

Also if you care about optimization, don't use anything under Eclipse Model game development. It's really the worst thing you can do, treating most of your game objects outside the map as scripts can yield significantly better and more dynamic results. Otherwise if you don't care about optimization use Orion cause its really only useful for prototyping or building small goof off games for yourself and a small audience to play and enjoy. I'd say the biggest achievement this engine offers is how diverse its development is between the whole collection of features as it allows you to get a wide variety of examples of coding people can learn around. Not all are super efficient in every case but still useful to have something you can be interested enough in to play with and still make an effort to learn to code useful content in at the same time.

Also to finish this comment off, Its vb.net. If it doesn't look like VB6 in some resemblance, then Microsoft needs to get off their ass and call the language by a different name cause it just isn't visual basic then.

EDIT: Forgot to mention my initial tip off that you may be trolling was the fact you said it crashed because XML documentation wasn't generated. That produces a warning and not a crash. Either you are incredibly inexperienced and don't know what you are talking about (And anything in your post shouldn't be taken seriously) or you are just literally trolling(Same outcome).

**Comment by ParchmentWolf** [comment]
@Damian666 I would recommend closing this after 2 or 3 days(To give the lad a chance to see my comment) I don't believe his comments should be taken seriously they honestly aren't all that reasonable and don't have very much thought put into them.

**Comment by ghost** [comment]
Sorry it looked like a troll, did not want to disregard his or her work, let alone brag about something, I just quoted my remakes not to say I'm some random trolling your git.
the orion is worth it because it has several systems already ready, and as mine is the naked e.o, I do not have time to add more algorithms, dynamic generation of maps, A* pathfinding etc.

DX Version, the first fully based on EO (UDP):
https://i.imgur.com/9nTCevL.png

SDL i have deleted totally because i forgot the backup in network migrate

SFML, the last (TCP+UDP):
https://i.imgur.com/lhmlhph.png
https://i.imgur.com/6Cyrrh9.png
https://i.imgur.com/JMOZGvr.png

i use windows forms to editors too.
im not joking, i want help, not hate him
and my actual project use ur sfml portable too :) 
sry english, google translate.

i have talk that look like vb6 because the sintaxe that he use.. i dont now.. its like php, u can code with ur methods but have too much unecessary things, if bool = true then, ifs instead switch, hover buttons with external images, if u look to code its the same of e.o with no optimizations in general

im in a group of friends that actually uses the E.O classic 2.0 vb6, and i make this engines for they, but i dont have time for complete now and i give ur project link because they aren't programmers.
we love Eclipse Engines and all robin, "jcsn" works since the first released engine.

i know that engines its for small projects, i have make various engines remakes to change this
i tested with lidgreen.network, winorcas, dotnet sockets, and the library graphics too, in final i think that sfml is the best for this.

anyway i dont work with programming, its just a hobby, i have another job and school etc that make me busy to finish all systems

really im so sorry if i have offended u, i dont speak english.. i dont know the 'tone' that i wrote.

**Comment by ParchmentWolf** [comment]
Eclipse is buggy and slow enough without the help of UDP making it spend more time and effort working on security... Not to mention Lidgren is just terrible unless you are using it like actual UDP(Not simulating TCP with secure reliable mode).

The network that used to be in Orion before I swapped to mine as significantly slower and had bugs it used try catches to get out of fixing(Which further slowed it down) which was raw sockets.. Making a network from scratch is pretty difficult to do well, mine I've spent a long time working on and will support anytime people find a problem with it to further produce a reliable royalty free network lib to PROPERLY compete with Lidgren.

Winsock orcas is terrible because it simply recreates network access/commands that vb6 had, not only does it not do it efficiently but it doesn't actually setup some form of network directly so its just a multi-layered wrapper. Wrappers lose performance on every layer and that's not something you want with something as performance sensitive as networking.

As far as I know quite a lot of features were migrated from VB6 by Damian666 to get the engine more feature full and if you find bugs no one has refused to fix them but they have to be reported. We have lives and don't play with this engine unless there's some major work to do or someone reports engine breaking bugs. You have to report them not just say "It's a buggy broken piece of crap fix it but it's up to you to find out what doesn't work." That isn't reasonable.

Finally, DirectX and SDL wouldn't be recommended for .net apps (At least not SDL directly) because DX is a Windows exclusive library that can't move cross platform with the help of Mono Framework, but it is also very complex which is a huge disadvantage when in a lot of cases it's already slower than OpenGL (even on older systems). SDL just doesn't have a friendly (or safe) .net implementation complete access to necessary functions (For example texture loading... Without a bunch of other unnecessary helper libraries you don't have any control over how they are loaded and therefor do not have the option to use your own method of encryption).
